import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'
import { auth } from '@/auth'
import { Noto_Sans_Georgian } from 'next/font/google'
import './globals.css'
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'

const font = Noto_Sans_Georgian({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={cn(font.className,
                "bg-red-300 dark:bg-[#313338]")}>
          <Toaster />
          <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          storageKey='chat-theme'
          >

          {children}

          </ThemeProvider>
         
        </body>
      </html>
    </SessionProvider>
  )
}
